sudo: required
services:
  - docker

before_install:
  - docker build -t degibbons/docker-react -f Dockerfile.dev .

script:
  - docker run degibbons/docker-react npm run test -- --coverage

# deploy: 
#   provider: elasticbeanstalk
#   region: (ex: "us-west-2")
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: (ex: "elasticbeanstalk-us-west-2-306476627547")
#   bucket_path: "docker"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"